// src/app/[locale]/info/facts/page.tsx
import { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';
import FactsContent from './content';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale });

  const title = t('facts.title');
  const description = t('seo.facts.description', {
    default: t('facts.intro'),
  });

  return {
    title: `${title} - ${t('meta.title', { default: 'Etage' })}`,
    description,
    openGraph: {
      title,
      description,
    },
  };
}

export default function FactsPage() {
  return <FactsContent />;
}

// pages/info/facts.vue
<template>
  <div>
    <h2>{{ $t("facts.title") }}</h2>
    <p>{{ $t("facts.intro") }}</p>
    <ul>
      <li>{{ $t("facts.fact1") }}</li>
      <li>{{ $t("facts.fact2") }}</li>
      <li>{{ $t("facts.fact3") }}</li>
      <li>{{ $t("facts.fact4") }}</li>
    </ul>
  </div>
</template>

<script>
definePageMeta({});

export default {
  name: "InfoFacts",
  head() {
    const title = this.$t("facts.title");
    const description = this.$t(`seo.facts.description`, {
      default: this.$t("facts.intro"),
    });

    return {
      title: `${title} - ${this.$t("meta.title", { default: "Etage" })}`,
      meta: [
        {
          hid: "description",
          name: "description",
          content: description,
        },
        {
          hid: "og:title",
          property: "og:title",
          content: title,
        },
        {
          hid: "og:description",
          property: "og:description",
          content: description,
        },
      ],
    };
  },
};
</script>
