// src/views/Main/sections/reviews/index.vue
<template>
  <ClientOnly>
    <section class="reviews">
      <div class="reviews__btnholder">
        <h2>{{ $t("reviews.title") }}</h2>
        <div
          id="feedback-btn"
          class="reviews__next reviews__next"
          @click.prevent="modalFeedbackOpen = true"
          v-if="!mobile && !tablet"
        >
          {{ $t("reviews.leaveReview") }}
        </div>
      </div>

      <div class="reviews__list">
        <div
          v-for="item in items"
          :key="item.feature"
          class="reviews__block"
          @click="openPopup(item.component)"
        >
          <svg-icon :name="item.svg" original class="reviews__icon" />

          <div class="reviews__title" v-html="item.feature"></div>

          <svg-icon name="chevron_feature" original class="reviews__chevron" />
        </div>
      </div>

      <div class="reviews__swiper">
        <div class="reviews__carousel" ref="carousel">
          <div
            v-for="(slide, index) in slides"
            :key="index"
            class="reviews__slide"
            @click="$eventbus.$emit('openPopup', 'PopupContentFeedback')"
          >
            <div class="reviews__slide-title">{{ slide.title }}</div>

            <p class="reviews__slide-desc dark-gray" v-line-clamp="3">
              {{ slide.desc }}
            </p>
          </div>
        </div>

        <button
          class="reviews__swiper-button reviews__swiper-button--prev"
          @click="scrollCarousel('prev')"
          :disabled="!canScrollPrev"
        ></button>
        <svg-icon
          name="divider"
          original
          v-if="mobile || tablet"
          class="reviews__swiper-divider"
        ></svg-icon>
        <button
          class="reviews__swiper-button reviews__swiper-button--next"
          @click="scrollCarousel('next')"
          :disabled="!canScrollNext"
        ></button>
      </div>

      <div class="reviews__btnholder">
        <div
          id="feedback-btn-mobile"
          class="reviews__next reviews__next"
          @click.prevent="modalFeedbackOpen = true"
          v-if="mobile || tablet"
        >
          {{ $t("reviews.leaveReview") }}
        </div>
      </div>
      <feedback-modal v-model="modalFeedbackOpen" />
    </section>
  </ClientOnly>
</template>

<script>
import { defineAsyncComponent } from "vue";

// Lazy load FeedbackModal - only loads when reviews section is active or modal is opened
export default {
  name: "AppPageMainSectionReviews",
  components: {
    FeedbackModal: defineAsyncComponent(() =>
      import("@/components/common/Feedback/app-feedback-modal")
    ),
  },
  props: {
    active: Boolean,
    mobile: Boolean,
    tablet: Boolean,
    desktop: Boolean,
  },
  watch: {
    mobile: "updateScrollButtons",
    tablet: "updateScrollButtons",
    desktop: "updateScrollButtons",
  },
  data: () => ({
    modalFeedbackOpen: false,
    currentIndex: 0,
  }),
  computed: {
    items() {
      return [
        {
          feature: this.$t("reviews.individualApproach"),
          svg: "individual_feature",
          component: "PopupContentAboutUs",
        },
        {
          feature: this.$t("reviews.teamSpecialists"),
          svg: "team_feature",
          component: "PopupContentSpecialists",
        },
        {
          feature: this.$t("reviews.professionalMaterials"),
          svg: "pack_feature",
          component: "PopupContentPackage",
        },
        {
          feature: this.$t("reviews.modernFleet"),
          svg: "auto_feature",
          component: "PopupContentAuto",
        },
        {
          feature: this.$t("reviews.transparentPricing"),
          svg: "price_feature",
          component: "PopupContentPayment",
        },
      ];
    },
    slides() {
      return [
        {
          title: this.$t("reviews.slides.slide1.title"),
          desc: this.$t("reviews.slides.slide1.desc"),
        },
        {
          title: this.$t("reviews.slides.slide2.title"),
          desc: this.$t("reviews.slides.slide2.desc"),
        },
        {
          title: this.$t("reviews.slides.slide3.title"),
          desc: this.$t("reviews.slides.slide3.desc"),
        },
        {
          title: this.$t("reviews.slides.slide4.title"),
          desc: this.$t("reviews.slides.slide4.desc"),
        },
        {
          title: this.$t("reviews.slides.slide5.title"),
          desc: this.$t("reviews.slides.slide5.desc"),
        },
        {
          title: this.$t("reviews.slides.slide6.title"),
          desc: this.$t("reviews.slides.slide6.desc"),
        },
      ];
    },
    canScrollPrev() {
      return this.currentIndex > 0;
    },
    canScrollNext() {
      if (this.mobile || this.tablet) {
        return this.currentIndex < this.slides.length - 1;
      }
      return this.currentIndex < this.slides.length - 3;
    },
  },
  mounted() {
    this.updateScrollButtons();
  },
  methods: {
    openPopup(e) {
      this.$eventbus.$emit("openPopup", e);
    },
    scrollCarousel(direction) {
      if (!this.$refs.carousel) return;

      const slideWidth = this.mobile || this.tablet ? 100 : 33.333;
      const container = this.$refs.carousel;
      const scrollAmount = (container.offsetWidth / 100) * slideWidth;

      if (direction === "next") {
        this.currentIndex = Math.min(
          this.currentIndex + 1,
          this.mobile || this.tablet
            ? this.slides.length - 1
            : this.slides.length - 3
        );
        container.scrollBy({ left: scrollAmount, behavior: "smooth" });
      } else {
        this.currentIndex = Math.max(this.currentIndex - 1, 0);
        container.scrollBy({ left: -scrollAmount, behavior: "smooth" });
      }
    },
    updateScrollButtons() {
      this.$nextTick(() => {
        if (this.$refs.carousel) {
          this.currentIndex = 0;
          this.$refs.carousel.scrollLeft = 0;
        }
      });
    },
  },
};
</script>

<style lang="scss">
.reviews {
  padding-top: 40px;

  h2 {
    margin-bottom: 36px;
  }

  .subtitle {
    margin-bottom: 50px;
  }

  &__list {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
  }

  &__block {
    width: 20%;
    display: flex;
    flex-direction: column;
    align-items: center;
    cursor: pointer;
  }

  &__title {
    text-align: center;
    font-family: var(--font-family-secondary);
    font-size: rem(16);
    font-weight: 500;
    letter-spacing: 0.3px;
  }

  &__icon {
    @include size(39px);
    margin-bottom: 10px;
  }

  &__chevron {
    height: 12px;
    margin-top: 12px;
  }

  &__swiper {
    margin-top: 70px;
    margin-bottom: 40px;
    position: relative;

    &::before {
      content: "";
      z-index: 10;
      display: block;
      position: absolute;
      left: -2px;
      top: 0;
      width: 200px;
      height: 100%;
      background-image: linear-gradient(
        to right,
        #ffffff 10%,
        rgba(255, 255, 255, 0)
      );
    }

    &::after {
      content: "";
      z-index: 10;
      display: block;
      position: absolute;
      right: -2px;
      top: 0;
      width: 200px;
      height: 100%;
      background-image: linear-gradient(
        to left,
        #ffffff 10%,
        rgba(255, 255, 255, 0)
      );
    }
  }

  &__carousel {
    display: flex;
    overflow-x: auto;
    scroll-snap-type: x mandatory;
    scroll-behavior: smooth;
    -webkit-overflow-scrolling: touch;
    gap: 70px;
    scrollbar-width: none;
    -ms-overflow-style: none;

    &::-webkit-scrollbar {
      display: none;
    }
  }

  &__swiper-divider {
    position: absolute;
    bottom: -48px;
    height: 28px;
    left: 50%;
    width: 35%;
    transform: translateX(-50%);
  }

  &__swiper-button {
    @include size(28px);
    background-color: var(--colors-accent);
    background-size: 8px 14px;
    background-position: center;
    background-repeat: no-repeat;
    border: none;
    border-radius: 50%;
    transform: translateY(-50%);
    margin-top: 0;
    cursor: pointer;
    position: absolute;
    top: 50%;
    z-index: 20;
    transition: opacity 0.3s;

    &--next {
      right: -30px;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 14'%3E%3Cpath fill='white' d='M1 0L0 1l6 6-6 6 1 1 7-7z'/%3E%3C/svg%3E");
    }

    &--prev {
      left: -30px;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 14'%3E%3Cpath fill='white' d='M7 0l1 1-6 6 6 6-1 1-7-7z'/%3E%3C/svg%3E");
    }

    &:hover:not(:disabled),
    &:focus:not(:disabled),
    &:active:not(:disabled) {
      outline: none;
      filter: brightness(1.1);
    }

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  }

  &__slide {
    text-align: center;
    width: 400px;
    min-width: 400px;
    cursor: pointer;
    scroll-snap-align: center;
  }

  &__slide-desc {
    line-height: 16px;
    word-break: normal !important;
  }

  &__slide-title {
    color: var(--colors-accent);
    font-size: rem(16);
    line-height: 1;
    letter-spacing: 0.3px;
    font-weight: bold;
    margin-bottom: 7px;
  }

  &__btnholder {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }

  &__next {
    background-color: var(--colors-accent);
    color: var(--white);
    height: 40px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0 30px;
    clip-path: polygon(0 0, calc(100% - 10px) 0, 100% 100%, 10px 100%);
    letter-spacing: 0.3px;
    font-weight: bold;
    cursor: pointer;
    transition: 0.3s ease-in-out;

    &--feedback {
      background-color: var(--colors-grey-200);
      color: var(--colors-text-primary);

      &:hover {
        color: var(--white);
        background-color: var(--colors-text-primary);
      }
    }

    & + & {
      margin-left: 10px;
    }

    svg {
      @include size(18px);
      margin-left: 14px;
      transition: 0.3s ease-in-out;
    }

    &:hover {
      filter: brightness(1.1);

      svg {
        transform: translateX(6px);
      }
    }
  }
}

@media screen and (min-width: 993px) and (max-height: 890px) {
  .reviews {
    padding-top: 0;

    .subtitle {
      margin-bottom: 30px;
    }

    &__icon {
      @include size(36px);
    }

    &__title {
      font-size: rem(14);
    }

    &__chevron {
      display: none;
    }

    &__swiper {
      margin-top: 60px;
      margin-bottom: 30px;
    }

    &__swiper-button {
      @include size(24px);
      background-size: 7px 12px;

      &--next {
        right: -26px;
      }

      &--prev {
        left: -26px;
      }
    }

    &__next {
      height: 38px;
    }
  }
}

@media screen and (min-width: 993px) and (max-height: 730px) {
  .reviews {
    padding-top: 10px;
  }
}

@media screen and (max-width: 993px) {
  .reviews {
    padding-top: 50px;

    h2 {
      margin-bottom: 10px;
    }

    .subtitle {
      margin-bottom: 20px;
    }

    &__list {
      flex-wrap: wrap;
    }

    &__block {
      width: calc(50% - 8px);
      margin-right: 16px;
      margin-bottom: 16px;
      height: 120px;
      background-color: var(--colors-grey-100);
      padding: 14px 9px 16px 9px;
      justify-content: center;
      margin-right: 0;

      &:nth-child(2) {
        order: -1;
        width: 100%;
      }
    }

    &__icon {
      @include size(39px);
      margin-bottom: 12px;
      flex-shrink: 0;
    }

    &__title {
      font-size: rem(12);
      font-weight: 500;
      letter-spacing: 0.2px;
      color: var(--colors-text-primary);
    }

    &__chevron {
      display: none;
    }

    &__swiper {
      margin-top: 50px;
      margin-bottom: 88px;

      &::before,
      &::after {
        display: none;
      }
    }

    &__carousel {
      gap: 0;
    }

    &__slide {
      width: 100%;
      min-width: 100%;
    }

    &__swiper-button {
      top: auto;
      bottom: -48px;
      transform: translateY(0);

      &--next {
        right: 20%;
      }

      &--prev {
        left: 20%;
      }
    }

    &__btnholder {
      flex-direction: column;
      align-items: center;
    }

    &__next {
      margin-top: 0;
      clip-path: none;

      & + & {
        margin-left: 0;
        margin-top: 16px;
      }
    }
  }
}
</style>

// src/views/Main/sections/reviews/index.tsx
"use client";

import React, { useState, useEffect, useRef } from "react";
import { useTranslations, useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import Button from "@/components/ui/Button/button";
import SvgIcon from "@/components/common/SvgIcon";
import dynamic from "next/dynamic";

const FeedbackModal = dynamic(
  () => import("@/components/common/Feedback/feedback-modal"),
  { ssr: false }
);

interface PageSectionReviewsProps {
  active?: boolean;
  mobile?: boolean;
  tablet?: boolean;
  desktop?: boolean;
}

export default function PageSectionReviews({
  active,
  mobile,
  tablet,
  desktop,
}: PageSectionReviewsProps) {
  const t = useTranslations();
  const locale = useLocale();
  const router = useRouter();
  const carouselRef = useRef<HTMLDivElement>(null);
  const [modalFeedbackOpen, setModalFeedbackOpen] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);

  const items = [
    {
      feature: t("reviews.individualApproach"),
      svg: "individual_feature",
      component: "PopupContentAboutUs",
    },
    {
      feature: t("reviews.teamSpecialists"),
      svg: "team_feature",
      component: "PopupContentSpecialists",
    },
    {
      feature: t("reviews.professionalMaterials"),
      svg: "pack_feature",
      component: "PopupContentPackage",
    },
    {
      feature: t("reviews.modernFleet"),
      svg: "auto_feature",
      component: "PopupContentAuto",
    },
    {
      feature: t("reviews.transparentPricing"),
      svg: "price_feature",
      component: "PopupContentPayment",
    },
  ];

  const slides = [
    {
      title: t("reviews.slides.slide1.title"),
      desc: t("reviews.slides.slide1.desc"),
    },
    {
      title: t("reviews.slides.slide2.title"),
      desc: t("reviews.slides.slide2.desc"),
    },
    {
      title: t("reviews.slides.slide3.title"),
      desc: t("reviews.slides.slide3.desc"),
    },
    {
      title: t("reviews.slides.slide4.title"),
      desc: t("reviews.slides.slide4.desc"),
    },
    {
      title: t("reviews.slides.slide5.title"),
      desc: t("reviews.slides.slide5.desc"),
    },
    {
      title: t("reviews.slides.slide6.title"),
      desc: t("reviews.slides.slide6.desc"),
    },
  ];

  const canScrollPrev = currentIndex > 0;
  const canScrollNext =
    mobile || tablet
      ? currentIndex < slides.length - 1
      : currentIndex < slides.length - 3;

  useEffect(() => {
    updateScrollButtons();
  }, [mobile, tablet]);

  const navigateToInfo = (route: string) => {
    router.push(`/${locale}/info/${route}`);
  };

  const openPopup = (component: string) => {
    const routeMap: { [key: string]: string } = {
      PopupContentAboutUs: "about_us",
      PopupContentSpecialists: "specialists",
      PopupContentPackage: "package",
      PopupContentAuto: "auto",
      PopupContentPayment: "payment",
      PopupContentFeedback: "reviews",
    };
    const route = routeMap[component] || "about_us";
    navigateToInfo(route);
  };

  const scrollCarousel = (direction: "prev" | "next") => {
    if (!carouselRef.current) return;

    const slideWidth = mobile || tablet ? 100 : 33.333;
    const container = carouselRef.current;
    const scrollAmount = (container.offsetWidth / 100) * slideWidth;

    if (direction === "next") {
      const newIndex = Math.min(
        currentIndex + 1,
        mobile || tablet ? slides.length - 1 : slides.length - 3
      );
      setCurrentIndex(newIndex);
      container.scrollBy({ left: scrollAmount, behavior: "smooth" });
    } else {
      const newIndex = Math.max(currentIndex - 1, 0);
      setCurrentIndex(newIndex);
      container.scrollBy({ left: -scrollAmount, behavior: "smooth" });
    }
  };

  const updateScrollButtons = () => {
    if (carouselRef.current) {
      setCurrentIndex(0);
      carouselRef.current.scrollLeft = 0;
    }
  };

  return (
    <section>
      <div className="flex justify-between items-start flex-col items-center lg:flex-row mb-9 lg:mb-6">
        <h2>{t("reviews.title")}</h2>
        {!mobile && !tablet && (
          <Button
            id="feedback-btn"
            variant="primary"
            size="lg"
            onClick={(e) => {
              e.preventDefault();
              setModalFeedbackOpen(true);
            }}
          >
            {t("reviews.leaveReview")}
          </Button>
        )}
      </div>

      <div className="flex items-start justify-between flex-wrap lg:flex-nowrap">
        {items.map((item, index) => (
          <div
            key={item.svg}
            className={`w-1/2 lg:w-1/5 flex-0 lg:flex-1 p-1 ${
              index === 1 ? "order-[-1] lg:order-none w-full lg:w-auto" : ""
            }`}
            onClick={() => openPopup(item.component)}
          >
            <div className="flex flex-col items-center justify-center cursor-pointer h-40 lg:h-auto bg-gray-100 dark:bg-gray-800 lg:!bg-transparent">
              <SvgIcon
                name={item.svg}
                original
                className="size-10 mb-4 lg:mb-3 flex-shrink-0"
              />
              <div
                className="text-center font-medium text-base lg:text-sm"
                dangerouslySetInnerHTML={{ __html: item.feature }}
              />
            </div>
          </div>
        ))}
      </div>

      <div className="mt-[70px] mb-10 relative max-lg:mt-[50px] max-lg:mb-[88px]">
        <div
          ref={carouselRef}
          className="flex overflow-x-auto scroll-smooth gap-[70px] [scrollbar-width:none] max-lg:gap-0 snap-x snap-mandatory [scroll-behavior:smooth]"
        >
          {slides.map((slide, index) => (
            <div
              key={index}
              className="text-center w-[400px] min-w-[400px] cursor-pointer snap-center max-lg:w-full max-lg:min-w-full"
              onClick={() => navigateToInfo("reviews")}
            >
              <h3 className="text-primary leading-none font-bold mb-4">
                {slide.title}
              </h3>
              <p className="text-gray-500 dark:text-gray-400 leading-5 text-base lg:text-sm break-normal line-clamp-3">
                {slide.desc}
              </p>
            </div>
          ))}
        </div>

        <Button
          variant="primary"
          size="lg"
          className="!size-8 !p-0 bg-primary bg-no-repeat bg-center absolute top-1/2 -translate-y-1/2 -left-16 bg-[length:8px_14px] max-lg:top-auto max-lg:bottom-[-48px] max-lg:translate-y-0 max-lg:left-[20%] [background-image:url('data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%208%2014%27%3E%3Cpath%20fill=%27white%27%20d=%27M7%200l1%201-6%206%206%206-1%201-7-7z%27/%3E%3C/svg%3E')]"
          onClick={() => scrollCarousel("prev")}
          disabled={!canScrollPrev}
          ariaLabel="Previous review"
        />
        <Button
          variant="primary"
          size="lg"
          className="!size-8 !p-0 bg-primary bg-no-repeat bg-center absolute top-1/2 -translate-y-1/2 -right-16 bg-[length:8px_14px] max-lg:top-auto max-lg:bottom-[-48px] max-lg:translate-y-0 max-lg:right-[20%] [background-image:url('data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%208%2014%27%3E%3Cpath%20fill=%27white%27%20d=%27M1%200L0%201l6%206-6%206%201%201%207-7z%27/%3E%3C/svg%3E')]"
          onClick={() => scrollCarousel("next")}
          disabled={!canScrollNext}
          ariaLabel="Next review"
        />
      </div>

      <div className="flex justify-between lg:items-start flex-col lg:flex-row items-center">
        {(mobile || tablet) && (
          <Button
            id="feedback-btn-mobile"
            variant="primary"
            size="lg"
            className="!px-6"
            onClick={(e) => {
              e.preventDefault();
              setModalFeedbackOpen(true);
            }}
          >
            {t("reviews.leaveReview")}
          </Button>
        )}
      </div>

      <FeedbackModal
        modelValue={modalFeedbackOpen}
        onUpdateModelValue={setModalFeedbackOpen}
      />
    </section>
  );
}
