// src/views/Main/sections/order/components/OrderFormComponent.tsx
'use client';

import React, { useState } from 'react';
import { useTranslations } from 'next-intl';
import Input from '@/components/ui/Input/input';
import Select from '@/components/ui/Select/select';
import Button from '@/components/ui/Button/button';
import { eventbus } from '@/lib/eventbus';

interface OrderFormComponentProps {
  mobile?: boolean;
  tablet?: boolean;
  onCloseModal?: () => void;
}

export default function OrderFormComponent({
  mobile,
  tablet,
  onCloseModal,
}: OrderFormComponentProps) {
  const t = useTranslations();
  const [name, setName] = useState<string | null>(null);
  const [phone, setPhone] = useState<string | null>(null);
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [workers, setWorkers] = useState<string | null>(null);
  const [type, setType] = useState<string | null>(null);
  const [date, setDate] = useState<string | null>(null);
  const [comment, setComment] = useState('');

  const transportOptions = [
    t('orderForm.transportOptions.flat'),
    t('orderForm.transportOptions.office'),
    t('orderForm.transportOptions.stuff'),
  ];

  const workersOptions = [
    t('orderForm.workersOptions.one'),
    t('orderForm.workersOptions.two'),
    t('orderForm.workersOptions.three'),
    t('orderForm.workersOptions.more'),
  ];

  const clearForm = () => {
    setName(null);
    setPhone(null);
    setFrom('');
    setTo('');
    setWorkers(null);
    setType(null);
    setDate(null);
    setComment('');
  };

  const handleSendEmail = async () => {
    if (name && phone) {
      try {
        const response = await fetch('/api/order', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name,
            phone,
            from,
            to,
            workers,
            type,
            date,
            comment,
          }),
        });

        if (response.ok) {
          clearForm();
          onCloseModal?.();
          eventbus.emit('openWelcomeModal');
        } else {
          console.error('Failed to send order');
        }
      } catch (error) {
        console.error('Failed to send order:', error);
      }
    }
  };

  return (
    <div className="order-form">
      <div className="flex flex-wrap">
        <div className="w-full lg:w-1/4">
          <Input
            id="order-name"
            value={name}
            onChange={setName}
            label={t('orderForm.nameLabel')}
            type="text"
            placeholder={t('orderForm.namePlaceholder')}
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Input
            id="order-phone"
            value={phone}
            onChange={setPhone}
            label={t('orderForm.phoneLabel')}
            type="text"
            placeholder={t('orderForm.phonePlaceholder')}
            isPhoneInput={true}
            mask="###-###-##-##"
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Input
            id="order-from"
            value={from}
            onChange={setFrom}
            label={t('orderForm.fromLabel')}
            type="text"
            placeholder={t('orderForm.fromPlaceholder')}
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Input
            id="order-date"
            value={date}
            onChange={setDate}
            label={t('orderForm.dateLabel')}
            type="text"
            placeholder={t('orderForm.datePlaceholder')}
            mask="##/##/#### ##:##"
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Select
            value={type}
            onChange={setType}
            label={t('orderForm.typeLabel')}
            placeholder={t('orderForm.typePlaceholder')}
            options={transportOptions}
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Select
            value={workers}
            onChange={setWorkers}
            label={t('orderForm.workersLabel')}
            placeholder={t('orderForm.workersPlaceholder')}
            options={workersOptions}
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Input
            id="order-to"
            value={to}
            onChange={setTo}
            label={t('orderForm.toLabel')}
            type="text"
            placeholder={t('orderForm.toPlaceholder')}
          />
        </div>

        <div className="w-full lg:w-1/4">
          <Input
            id="order-comment"
            value={comment}
            onChange={setComment}
            label={t('orderForm.commentLabel')}
            type="text"
            placeholder={t('orderForm.commentPlaceholder')}
          />
        </div>

        <div className="w-full">
          <Button
            id="order-form-btn"
            variant="primary"
            size="lg"
            className="w-full lg:w-auto"
            disabled={!phone || !name}
            onClick={handleSendEmail}
          >
            {t('common.submit')}
          </Button>
        </div>
      </div>
    </div>
  );
}

// src/views/Main/sections/order/components/OrderFormComponent.vue
<template>
  <form class="order-form">
    <div class="mobile-wrapper">
      <template v-if="mobile || tablet">
        <div class="order-form__close" @click="$emit('closeModal')"></div>

        <div class="order-form__title">
          <h2>{{ $t("orderForm.title") }}</h2>
          <div class="subtitle">{{ $t("orderForm.subtitle") }}</div>
        </div>
      </template>

      <div class="row" v-if="unsend">
        <div class="col-lg-3">
          <app-input
            :requiredField="!name && name !== null"
            v-model="name"
            :label="$t('orderForm.nameLabel')"
            type="text"
            :placeholder="$t('orderForm.namePlaceholder')"
          />
        </div>

        <div class="col-lg-3">
          <app-input
            :requiredField="!phone && phone !== null"
            v-model="phone"
            :label="$t('orderForm.phoneLabel')"
            type="text"
            :placeholder="$t('orderForm.phonePlaceholder')"
            mask="###-###-##-##"
          />
        </div>

        <div class="col-lg-3">
          <app-input
            v-model="from"
            :label="$t('orderForm.fromLabel')"
            type="text"
            :placeholder="$t('orderForm.fromPlaceholder')"
          />
        </div>

        <div class="col-lg-3">
          <app-input
            v-model="date"
            :label="$t('orderForm.dateLabel')"
            type="text"
            :placeholder="$t('orderForm.datePlaceholder')"
            mask="##/##/#### ##:##"
          />
        </div>

        <div class="col-lg-3">
          <app-select
            v-model="type"
            :label="$t('orderForm.typeLabel')"
            :placeholder="$t('orderForm.typePlaceholder')"
            :options="transport.options"
            :value="transport.value"
          ></app-select>
        </div>

        <div class="col-lg-3">
          <app-select
            v-model="workers"
            :label="$t('orderForm.workersLabel')"
            :placeholder="$t('orderForm.workersPlaceholder')"
            :options="stuff.options"
            :value="stuff.value"
          ></app-select>
        </div>

        <div class="col-lg-3">
          <app-input
            v-model="to"
            :label="$t('orderForm.toLabel')"
            type="text"
            :placeholder="$t('orderForm.toPlaceholder')"
          />
        </div>

        <div class="col-lg-3">
          <app-input
            v-model="comment"
            :label="$t('orderForm.commentLabel')"
            type="text"
            :placeholder="$t('orderForm.commentPlaceholder')"
          />
        </div>
      </div>
      <welcome-modal v-model="modalWelcomeOpen" />
      <div class="order-form__btn-wrapper" v-if="unsend">
        <button
          id="order-form-btn"
          class="order-form__button"
          :disabled="!phone || !name"
          @click.prevent="handleSendEmail"
        >
          {{ $t("common.submit") }}
        </button>
      </div>
    </div>
  </form>
</template>

<script>
import axios from 'axios';
import WelcomeModal from '@/components/common/Welcome/app-welcome-modal';

export default {
  name: 'SectionOrderFormComponent',
  components: {
    WelcomeModal,
  },
  props: {
    mobile: Boolean,
    tablet: Boolean,
  },
  data() {
    return {
      name: null,
      phone: null,
      from: '',
      to: '',
      workers: null,
      type: null,
      date: null,
      comment: '',
      unsend: true,
      modalWelcomeOpen: true,
    };
  },
  computed: {
    transport() {
      return {
        options: [
          this.$t('orderForm.transportOptions.flat'),
          this.$t('orderForm.transportOptions.office'),
          this.$t('orderForm.transportOptions.stuff'),
        ],
        value: null,
      };
    },
    stuff() {
      return {
        options: [
          this.$t('orderForm.workersOptions.one'),
          this.$t('orderForm.workersOptions.two'),
          this.$t('orderForm.workersOptions.three'),
          this.$t('orderForm.workersOptions.more'),
        ],
        value: null,
      };
    },
  },
  mounted() {
    this.modalWelcomeOpen = false;
  },
  methods: {
    handleSendEmail() {
      if (this.name && this.phone) {
        axios({
          url: 'https://etage.com.ua/api/order',
          method: 'post',
          data: {
            name: this.name,
            phone: this.phone,
            from: this.from,
            to: this.to,
            workers: this.workers,
            type: this.type,
            date: this.date,
            comment: this.comment,
          },
        });

        this.unsend = false;
        this.modalWelcomeOpen = true;
      }
    },
  },
};
</script>

<style lang="scss">
.order-form {
  margin-top: 30px;

  &__button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 13px 20px;
    font-size: rem(14);
    font-weight: bold;
    line-height: 1;
    letter-spacing: 0.3px;
    color: $white;
    border: none;
    box-shadow: none;
    background-color: var(--colors-accent);

    &:hover,
    &:focus,
    &:active {
      outline: none;
    }
  }

  &__after {
    font-size: rem(14);
    color: var(--colors-text-primary);
  }
}

@media screen and (max-width: 992px) {
  .order-form {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    min-height: 100vh;
    max-height: 100vh;
    overflow: auto;
    z-index: 999999;
    background-color: #fff;
    margin-top: 0;
    padding: 0 16px;

    &__close {
      @include size(16px);
      overflow: hidden;
      position: absolute;
      top: 16px;
      right: 0;

      &::before {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotateZ(-45deg);
        @include size(20px, 2px);
        background-color: var(--colors-text-primary);
      }

      &::after {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotateZ(45deg);
        @include size(20px, 2px);
        background-color: var(--colors-text-primary);
      }
    }

    &__btn-wrapper {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      margin-bottom: 40px;
    }
  }
}
</style>
