// src/views/Main/sections/price/index.vue
<template>
  <ClientOnly>
    <div class="price">
      <h2>{{ $t("price.title") }}</h2>

      <div class="subtitle dark-gray price__header--mobile">
        <a href="#" @click.prevent="navigateToInfo('auto')">{{
          $t("price.mobileSubtitle1")
        }}</a>
        {{ $t("price.mobileSubtitle2") }}

        <a href="#" @click.prevent="navigateToInfo('specialists')">{{
          $t("price.mobileSubtitle3")
        }}</a>
        {{ $t("price.mobileSubtitle4") }}

        <a href="#" @click.prevent="navigateToInfo('package')">{{
          $t("price.mobileSubtitle5")
        }}</a>
      </div>

      <div class="price__header">
        <div class="price__header-block subtitle dark-gray">
          <svg-icon name="icon_1" original />
          <a href="#" @click.prevent="navigateToInfo('auto')">{{
            $t("price.desktopSubtitle1")
          }}</a>
          &nbsp;{{ $t("price.desktopSubtitle2") }}
        </div>
        <div class="price__header-block subtitle dark-gray">
          <svg-icon name="icon_2" original />
          {{ $t("price.desktopSubtitle3") }}&nbsp;
          <a href="#" @click.prevent="navigateToInfo('specialists')">{{
            $t("price.desktopSubtitle4")
          }}</a>
        </div>
        <div class="price__header-block subtitle dark-gray">
          <svg-icon name="icon_3" original />
          {{ $t("price.desktopSubtitle5") }}&nbsp;
          <a href="#" @click.prevent="navigateToInfo('package')">{{
            $t("price.desktopSubtitle6")
          }}</a>
        </div>
      </div>

      <div class="row" v-if="!mobile && !tablet">
        <div class="col-lg-8">
          <div class="price__subtitle-wrapper">
            <div
              class="price__subtitle price__subtitle--tree"
              @click="navigateToInfo('auto')"
            >
              {{ $t("price.carRental") }}
              <svg-icon name="link" original />
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="price__subtitle" @click="navigateToInfo('specialists')">
            {{ $t("price.specialistsServices") }}
            <svg-icon name="link" original />
          </div>
        </div>
      </div>

      <div class="row" v-if="mobile || tablet">
        <div v-for="category in categories" :key="category.name" class="col-12">
          <div class="category-mini p-4 flex flex-col mb-4">
            <div class="flex items-center mb-4">
              <svg-icon
                :name="category.iconName"
                class="category-mini__icon"
                original
              />
              <div class="category-mini__info">
                <h3 class="capitalize">
                  {{ category.name }}
                </h3>
                <p class="category-mini__subtitle dark-gray">
                  {{ category.subtitle }}
                </p>
              </div>
            </div>
            <div
              class="category__price-wrapper"
              v-for="item in category.items"
              :key="item.id"
            >
              <div class="category__additional" v-if="item.additional">
                {{ item.additional }}
              </div>

              <div class="category__price">
                <div class="category__tooltip-wrapper">
                  <span class="category__price-value"
                    >{{ item.time }}&nbsp;</span
                  >
                  <span
                    class="category__price-value category__price-value--highlighted"
                    >{{ item.price }}</span
                  >

                  <div class="category__tooltip" v-if="item.info">
                    <svg-icon name="info" />
                    <div class="category__info">{{ item.info }}</div>
                  </div>
                </div>

                <p class="category__description">{{ item.description }}</p>
              </div>
            </div>
            <p class="category__undertext">{{ category.undertext }}</p>
            <div class="row justify-center">
              <div
                v-if="mobile"
                @click="openForm(category)"
                class="price__examples price__examples--mobile"
              >
                {{ $t("price.orderButton") }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row items-stretch">
        <div
          v-for="category in categories"
          :key="category.name"
          class="col-lg-4"
        >
          <transition name="component-fade">
            <div v-if="!mobile && !tablet" class="price__category category">
              <div class="mobile-wrapper">
                <div class="category__header-wrapper">
                  <h3 class="category__title">{{ category.name }}</h3>
                  <div
                    class="category__tooltip category__tooltip--small-screens"
                  >
                    <svg-icon name="info" />
                    <div class="category__info">{{ category.undertext }}</div>
                  </div>
                </div>

                <p class="category__subtitle">{{ category.subtitle }}</p>

                <svg-icon
                  :name="category.iconName"
                  class="category__icon"
                  original
                />
              </div>

              <div
                class="category__price-wrapper"
                v-for="item in category.items"
                :key="item.id"
              >
                <div class="category__additional" v-if="item.additional">
                  {{ item.additional }}
                </div>

                <div class="category__price">
                  <div class="category__tooltip-wrapper">
                    <span class="category__price-value"
                      >{{ item.time }}&nbsp;</span
                    >
                    <span
                      class="category__price-value category__price-value--highlighted"
                      >{{ item.price }}</span
                    >

                    <div class="category__tooltip" v-if="item.info">
                      <svg-icon name="info" />
                      <div class="category__info">{{ item.info }}</div>
                    </div>
                  </div>

                  <p class="category__description">{{ item.description }}</p>
                </div>
              </div>
            </div>
          </transition>
        </div>
      </div>

      <div class="row justify-center">
        <div class="price__examples" @click="navigateToInfo('flat_move')">
          {{ $t("price.examplesButton") }}
          <svg-icon name="arrow-next" />
        </div>
      </div>
    </div>
  </ClientOnly>
</template>

<script>
export default {
  name: "AppPageMainSectionPrice",
  props: {
    active: Boolean,
    mobile: Boolean,
    tablet: Boolean,
  },
  computed: {
    categories() {
      return [
        {
          name: this.$t("price.categoryTransport"),
          subtitle: this.$t("price.categoryTransportSubtitle"),
          undertext: this.$t("price.categoryTransportUndertext"),
          iconName: "price_transport",
          route: "auto",
          opened: false,
          items: [
            {
              id: 1,
              time: this.$t("price.categoryTransportItem1Time"),
              price: this.$t("price.categoryTransportItem1Price"),
              description: this.$t("price.categoryTransportItem1Desc"),
              info: this.$t("price.categoryTransportItem1Info"),
            },
            {
              id: 2,
              time: this.$t("price.categoryTransportItem2Time"),
              price: this.$t("price.categoryTransportItem2Price"),
              description: this.$t("price.categoryTransportItem2Desc"),
            },
          ],
        },
        {
          name: this.$t("price.categoryMove"),
          subtitle: this.$t("price.categoryMoveSubtitle"),
          undertext: this.$t("price.categoryMoveUndertext"),
          iconName: "price_moving",
          route: "flat_move",
          opened: false,
          items: [
            {
              id: 1,
              time: this.$t("price.categoryMoveItem1Time"),
              price: this.$t("price.categoryMoveItem1Price"),
              description: this.$t("price.categoryMoveItem1Desc"),
              additional: this.$t("price.categoryMoveItem1Additional"),
              info: this.$t("price.categoryMoveItem1Info"),
            },
            {
              id: 2,
              time: this.$t("price.categoryMoveItem2Time"),
              price: this.$t("price.categoryMoveItem2Price"),
              description: this.$t("price.categoryMoveItem2Desc"),
              additional: this.$t("price.categoryMoveItem2Additional"),
            },
          ],
        },
        {
          name: this.$t("price.categoryWorkers"),
          subtitle: this.$t("price.categoryWorkersSubtitle"),
          undertext: this.$t("price.categoryWorkersUndertext"),
          iconName: "price_workers",
          route: "specialists",
          opened: false,
          items: [
            {
              id: 1,
              time: this.$t("price.categoryWorkersItem1Time"),
              price: this.$t("price.categoryWorkersItem1Price"),
              description: this.$t("price.categoryWorkersItem1Desc"),
              info: this.$t("price.categoryWorkersItem1Info"),
            },
            {
              id: 2,
              time: this.$t("price.categoryWorkersItem2Time"),
              price: this.$t("price.categoryWorkersItem2Price"),
            },
          ],
        },
      ];
    },
  },
  data: () => ({}),
  methods: {
    navigateToInfo(route) {
      const locale = this.$i18n?.locale || "ua";
      if (this.$router) {
        this.$router.push(`/${locale}/info/${route}`);
      }
    },
    handleCloseFullSize(e) {
      e.opened = false;
      document.body.classList.remove("modal-open");
    },

    handleOpenFullSize(e) {
      e.opened = true;
      document.body.classList.add("modal-open");
    },

    openForm(e) {
      this.handleOpenFullSize(e);
      e.opened = false;
      this.$eventbus.$emit("openFormModal");
    },
  },
};
</script>

<style lang="scss">
.price {
  padding-top: 40px;

  h2 {
    margin-bottom: 16px;
  }

  .subtitle {
    margin-bottom: 16px;
  }

  &__header {
    display: flex;
    align-items: center;
    margin-bottom: 16px;

    &--mobile {
      display: none;
    }

    svg {
      height: 18px;
      margin-right: 6px;
    }

    .price__header-block + .price__header-block {
      margin-left: 24px;
      position: relative;

      &::before {
        content: "+";
        position: absolute;
        left: -12px;
        top: 50%;
        transform: translate(-50%, -50%);
      }
    }
  }

  &__header-block {
    margin-bottom: 0;
    font-size: rem(13);
    background-color: var(--colors-grey-200);
    height: 36px;
    padding: 0 10px;
    display: flex;
    align-items: center;
  }

  &__subtitle-wrapper {
    display: flex;
    justify-content: center;
  }

  &__subtitle {
    color: var(--colors-text-secondary);
    font-family: var(--font-family-secondary);
    font-size: rem(18);
    font-weight: bold;
    letter-spacing: 0.4px;
    text-align: center;
    margin-bottom: 18px;
    position: relative;
    cursor: pointer;

    &--tree {
      &::before {
        content: "";
        display: block;
        position: absolute;
        top: 50%;
        right: calc(100% + 20px);
        @include size(84px, 20px);
        border-top: 2px solid #e8e8e8;
        border-left: 2px solid #e8e8e8;
      }

      &::after {
        content: "";
        display: block;
        position: absolute;
        top: 50%;
        left: calc(100% + 20px);
        @include size(84px, 20px);
        border-top: 2px solid #e8e8e8;
        border-right: 2px solid #e8e8e8;
      }
    }

    svg {
      @include size(12px);
      margin-left: 2px;
    }
  }

  &__examples {
    margin-top: 34px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 13px 20px;
    background-color: var(--colors-accent);
    color: var(--white);
    font-size: rem(14);
    font-weight: 600;
    line-height: 1;
    letter-spacing: 0.3px;
    transition: 0.3s ease-in-out;
    cursor: pointer;

    &--mobile {
      padding: 12px 38px;
      margin-top: 52px;
    }

    svg {
      @include size(18px);
      margin-left: 14px;
      transition: 0.3s ease-in-out;
      fill: #fff;
    }

    &:hover {
      color: var(--white);
      filter: brightness(1.1);

      svg {
        transform: translateX(6px);
      }
    }
  }
}

.category {
  background-color: var(--colors-grey-100);
  padding: 10px 20px 20px 20px;
  position: relative;
  height: 100%;

  &__subtitle {
    letter-spacing: 0.3px;
    max-width: 280px;
    margin-bottom: 12px;
  }

  &__icon {
    @include size(40px);
    position: absolute;
    right: 20px;
    top: 20px;
  }

  &__price-wrapper {
    display: flex;
    align-items: center;

    &:not(:last-of-type) {
      margin-bottom: 14px;
    }
  }

  &__additional {
    @include size(72px, 37px);
    margin-right: 12px;
    background-color: var(--white);
    clip-path: polygon(79% 0, 100% 50%, 80% 100%, 0 100%, 0 0);
    padding-left: 9px;
    line-height: 37px;
    font-family: var(--font-family-secondary);
    font-size: rem(16);
    font-weight: 800;
    letter-spacing: 0.4px;
    color: var(--colors-accent);
  }

  &__price-value {
    font-family: var(--font-family-secondary);
    font-size: rem(19);
    font-weight: bold;
    letter-spacing: 0.4px;

    &--highlighted {
      color: var(--colors-accent);
    }
  }

  &__undertext {
    margin-top: 20px;
    color: var(--colors-text-secondary);
  }

  &__header-wrapper {
    display: flex;
    align-items: center;

    .category__tooltip {
      margin-top: -3px;
    }
  }

  &__tooltip-wrapper {
    display: flex;
    align-items: center;
  }

  &__tooltip {
    position: relative;
    margin-left: 8px;
    cursor: pointer;
    display: inline;

    &--small-screens {
      display: none;
    }

    svg {
      @include size(16px);
      fill: #d0d0d0;
      transition: 0.3s ease-in-out;
    }

    &:hover {
      svg {
        fill: var(--colors-accent);
      }

      .category__info {
        display: block;
      }
    }
  }

  &__info {
    position: absolute;
    box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.1);
    background-color: var(--colors-text-primary);
    color: var(--white);
    border-radius: 4px;
    width: 184px;
    padding: 10px 14px;
    font-size: rem(12);
    bottom: calc(100% + 8px);
    left: 50%;
    transform: translate(-50%);
    display: none;

    &::before {
      content: "";
      position: absolute;
      bottom: -5px;
      @include size(10px);
      background-color: var(--colors-text-primary);
      left: 50%;
      transform: translateX(-50%) rotateZ(45deg);
    }
  }
}

.category-mini {
  &__icon {
    @include size(60px);
    margin-right: 16px;
    flex-shrink: 0;
    transition: 0.3s ease-in-out;
  }
}

@media screen and (min-width: 993px) and (max-height: 890px) {
  .price {
    padding-top: 0;

    &__subtitle {
      font-size: rem(16);
    }

    &__examples {
      height: 38px;
    }
  }

  .category {
    &__price-value {
      font-size: rem(17);
    }

    &__price-wrapper {
      margin-bottom: 0 !important;

      & + & {
        margin-top: 14px;
      }
    }

    &__icon {
      @include size(35px);
      top: 16px;
      right: 16px;
    }

    &__subtitle {
      max-width: calc(100% - 20px);
    }

    &__undertext {
      display: none;
    }

    &__tooltip {
      &--small-screens {
        display: block;

        svg {
          fill: var(--colors-accent);
          animation: pulse 0.6s 2s 3;
        }

        &:hover {
          svg {
            animation: none;
          }
        }

        .category__info {
          width: 250px;
        }
      }
    }
  }
}

@media screen and (min-width: 993px) and (max-height: 770px) {
  .price {
    padding-top: 10px;

    &__header {
      margin-bottom: 0;

      svg {
        height: 14px;
      }
    }

    &__header-block {
      height: 30px;
      font-size: rem(11);
    }

    &__examples {
      margin-top: 25px;
    }
  }
}

@media screen and (min-width: 993px) and (max-height: 730px) {
  .price {
    padding-top: 10px;

    &__header {
      margin-bottom: 0;
    }
  }
}

@media screen and (max-width: 992px) {
  .price {
    &__header {
      display: none;

      &--mobile {
        display: block;
      }
    }
  }

  .category {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    z-index: 100000;
    padding: 0 16px 0 16px;

    h3 {
      font-size: rem(22);
      font-weight: 800;
      letter-spacing: 0.4px;
      margin-bottom: 4px;
    }

    &__subtitle {
      color: var(--colors-text-primary);
      max-width: 250px;
    }

    &__undertext {
      margin-top: 20px;
      padding: 0;
    }

    &__close {
      @include size(16px);
      overflow: hidden;
      position: absolute;
      top: 16px;
      right: 0;

      &::before {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotateZ(-45deg);
        @include size(20px, 2px);
        background-color: var(--colors-text-primary);
      }

      &::after {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotateZ(45deg);
        @include size(20px, 2px);
        background-color: var(--colors-text-primary);
      }
    }

    &__icon {
      @include size(50px);
      top: 105px;
      right: 10px;
    }
  }
}

@media screen and (max-width: 767px) {
  .category {
    padding: 0 16px 0 16px;

    &__close {
      top: 16px;
      right: 0;
    }

    &__icon {
      @include size(50px);
      top: 60px;
      right: 0px;
    }
  }
}
</style>

// src/views/Main/sections/price/index.tsx
"use client";

import React from "react";
import { useTranslations, useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Button from "@/components/ui/Button/button";
import SvgIcon from "@/components/common/SvgIcon";
import { eventbus } from "@/lib/eventbus";

interface PageSectionPriceProps {
  active?: boolean;
  mobile?: boolean;
  tablet?: boolean;
  desktop?: boolean;
}

export default function PageSectionPrice({
  active,
  mobile,
  tablet,
  desktop,
}: PageSectionPriceProps) {
  const t = useTranslations();
  const locale = useLocale();
  const router = useRouter();

  const categories2 = [
    {
      iconName: "icon_1",
      parts: [
        { type: "link", text: t("price.desktopSubtitle1"), route: "auto" },
        { type: "text", text: t("price.desktopSubtitle2") },
      ],
    },
    {
      iconName: "icon_2",
      parts: [
        { type: "text", text: t("price.desktopSubtitle3") },
        {
          type: "link",
          text: t("price.desktopSubtitle4"),
          route: "specialists",
        },
      ],
    },
    {
      iconName: "icon_3",
      parts: [
        { type: "text", text: t("price.desktopSubtitle5") },
        { type: "link", text: t("price.desktopSubtitle6"), route: "package" },
      ],
    },
  ];

  const categories = [
    {
      name: t("price.categoryTransport"),
      subtitle: t("price.categoryTransportSubtitle"),
      undertext: t("price.categoryTransportUndertext"),
      iconName: "price_transport",
      route: "auto",
      items: [
        {
          id: 1,
          time: t("price.categoryTransportItem1Time"),
          price: t("price.categoryTransportItem1Price"),
          description: t("price.categoryTransportItem1Desc"),
          info: t("price.categoryTransportItem1Info"),
        },
        {
          id: 2,
          time: t("price.categoryTransportItem2Time"),
          price: t("price.categoryTransportItem2Price"),
          description: t("price.categoryTransportItem2Desc"),
        },
      ],
    },
    {
      name: t("price.categoryMove"),
      subtitle: t("price.categoryMoveSubtitle"),
      undertext: t("price.categoryMoveUndertext"),
      iconName: "price_moving",
      route: "flat_move",
      items: [
        {
          id: 1,
          time: t("price.categoryMoveItem1Time"),
          price: t("price.categoryMoveItem1Price"),
          description: t("price.categoryMoveItem1Desc"),
          additional: t("price.categoryMoveItem1Additional"),
          info: t("price.categoryMoveItem1Info"),
        },
        {
          id: 2,
          time: t("price.categoryMoveItem2Time"),
          price: t("price.categoryMoveItem2Price"),
          description: t("price.categoryMoveItem2Desc"),
          additional: t("price.categoryMoveItem2Additional"),
        },
      ],
    },
    {
      name: t("price.categoryWorkers"),
      subtitle: t("price.categoryWorkersSubtitle"),
      undertext: t("price.categoryWorkersUndertext"),
      iconName: "price_workers",
      route: "specialists",
      items: [
        {
          id: 1,
          time: t("price.categoryWorkersItem1Time"),
          price: t("price.categoryWorkersItem1Price"),
          description: t("price.categoryWorkersItem1Desc"),
          info: t("price.categoryWorkersItem1Info"),
        },
        {
          id: 2,
          time: t("price.categoryWorkersItem2Time"),
          price: t("price.categoryWorkersItem2Price"),
        },
      ],
    },
  ];

  const getInfoRoute = (route: string) => {
    return `/${locale}/info/${route}`;
  };

  const navigateToInfo = (route: string) => {
    router.push(`/${locale}/info/${route}`);
  };

  const openForm = () => {
    eventbus.emit("openFormModal");
  };

  return (
    <div>
      <h2 className="mb-6">{t("price.title")}</h2>

      <div className="text-gray-800 dark:text-gray-300 flex items-center flex-wrap lg:flex-nowrap gap-3 mb-6">
        {categories2.map((category, index) => (
          <div
            key={index}
            className="flex items-center gap-3 text-lg lg:text-sm"
          >
            <div className="lg:bg-gray-100 lg:dark:bg-gray-800 lg:py-2 lg:px-4 flex items-center">
              {!mobile && !tablet && (
                <SvgIcon
                  name={category.iconName}
                  className="size-5 mr-3"
                  original
                />
              )}
              {category.parts.map((part, partIndex) => (
                <React.Fragment key={partIndex}>
                  {partIndex > 0 && <>&nbsp;</>}
                  {part.type === "link" && part.route ? (
                    <Link href={getInfoRoute(part.route)} className="link">
                      {part.text}
                    </Link>
                  ) : (
                    <span>{part.text}</span>
                  )}
                </React.Fragment>
              ))}
            </div>
            {index < categories2.length - 1 && (
              <div className="text-gray-300">+</div>
            )}
          </div>
        ))}
      </div>

      <div className="hidden lg:flex text-gray-500 dark:text-gray-400 font-bold text-sm text-center">
        <div className="w-2/3 flex justify-center">
          <div
            className="mb-3 relative cursor-pointer before:content-[''] before:block before:absolute before:top-1/2 before:right-[calc(100%+20px)] before:w-[84px] before:h-5 before:border-t-2 before:border-l-2 before:border-gray-200 dark:before:border-gray-600 after:content-[''] after:block after:absolute after:top-1/2 after:left-[calc(100%+20px)] after:w-[84px] after:h-5 after:border-t-2 after:border-r-2 after:border-gray-200 dark:after:border-gray-600"
            onClick={() => navigateToInfo("auto")}
          >
            {t("price.carRental")}
            <SvgIcon name="link" className="size-3 ml-1" original />
          </div>
        </div>

        <div className="w-1/3">
          <div
            className="mb-3 relative cursor-pointer"
            onClick={() => navigateToInfo("specialists")}
          >
            {t("price.specialistsServices")}
            <SvgIcon name="link" className="size-3 ml-1" original />
          </div>
        </div>
      </div>

      <div className="flex flex-wrap lg:flex-nowrap gap-4">
        {categories.map((category) => (
          <div key={category.name} className="w-full lg:w-1/3">
            <div className="bg-gray-100 dark:bg-gray-800 h-full p-5 lg:py-2">
              <div className="flex items-center gap-4">
                <SvgIcon
                  name={category.iconName}
                  className="size-16 lg:size-12 lg:order-last flex-shrink-0"
                  original
                />
                <div>
                  <h3>{category.name}</h3>
                  <p className="text-base leading-1 lg:text-sm text-gray-500 dark:text-gray-400 lg:max-w-[90%]">
                    {category.subtitle}
                  </p>
                </div>
              </div>

              {category.items.map((item) => (
                <div key={item.id} className="flex items-center my-4">
                  {"additional" in item && item.additional && (
                    <div className="w-20 h-10 flex items-center justify-center pr-2 mr-3 bg-white dark:bg-gray-700 [clip-path:polygon(79%_0,100%_50%,80%_100%,0_100%,0_0)] text-base font-bold text-primary">
                      {item.additional}
                    </div>
                  )}

                  <div>
                    <div className="flex items-center text-lg font-bold">
                      <span>{item.time}&nbsp;</span>
                      <span className="text-primary">{item.price}</span>

                      {item.info && (
                        <div className="relative ml-3 cursor-pointer group">
                          <SvgIcon name="info" className="size-5" />
                          <div className="absolute hidden z-[9999999] lg:text-sm group-hover:block bg-gray-900 text-white rounded w-80 px-4 py-2 text-base font-normal bottom-full mb-2 left-1/2 -translate-x-1/2 before:content-[''] before:absolute before:-bottom-[5px] before:size-3 before:bg-inherit before:left-1/2 before:-translate-x-1/2 before:rotate-45">
                            {item.info}
                          </div>
                        </div>
                      )}
                    </div>

                    {item.description && (
                      <p className="text-gray-500 dark:text-gray-400 lg:text-sm">
                        {item.description}
                      </p>
                    )}
                  </div>
                </div>
              ))}

              <p className="lg:hidden my-5 text-gray-600 dark:text-gray-200">
                {category.undertext}
              </p>

              {(mobile || tablet) && (
                <Button
                  variant="primary"
                  size="lg"
                  className="w-full"
                  onClick={openForm}
                >
                  {t("price.orderButton")}
                </Button>
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="flex justify-center">
        <Button
          variant="primary"
          size="lg"
          className="mt-12"
          onClick={() => navigateToInfo("flat_move")}
        >
          {t("price.examplesButton")}
          <SvgIcon name="arrow-next" className="size-4 ml-2" original />
        </Button>
      </div>
    </div>
  );
}
